### ISSUE TITLE
data time

### ISSUE THREAD

**Issue by gedw99** [iredmail/goutils#50]
https://github.com/golang-module/carbon could be used to give all aspects the ability to convert datas and times.

For example between the DB and the GUI we need to convert UTC and User Date and Time.

**Comment by iredmail** [comment]
Hi @gedw99 

Thanks for sharing. We just need few small functions to handle the time, no bother to import an external third-party module. :)

**Comment by gedw99** [comment]
Can you give me an idea of what functions ?

**Comment by iredmail** [comment]
> Can you give me an idea of what functions ?

https://github.com/iredmail/goutils/blob/main/timeutils/timeutils.go

By the way, this is a personal Go module with few useful functions for personal use, you should not use it in your Go project.

**Comment by gedw99** [comment]
Ah so you don’t want PR’s ?

**Comment by iredmail** [comment]
We accept PRs to fix / improve existing code, but we do not accept PRs to implement NEW features, because this repo is for personal use. :)

**Comment by gedw99** [comment]
OK got it.

So I look at that functions in timeutils.go and they are not called from anything so no point me extending them.

thanks

**Comment by iredmail** [comment]
> So I look at that functions in timeutils.go and they are not called from anything so no point me extending them.

this `goutils` module is mostly used by our other projects, for example, Spider Email Archiver (https://spiderd.io), and upcoming `iRedMail Enterprise` (https://docs.iredmail.org/pro.html), and few other Go projects which are not yet public.

**Comment by gedw99** [comment]
Sounds like big plans. 

all makes sense .

Anyways this is closed issue.
